services:
  - type: web
    name: mern-ecommerce-backend
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://sujalporte68:CiljLxHoThzZ2vF8@cluster0.15h9xv1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: d88c43e235d308c0826e4818b5d91f67 